name: Continuous Integration

# Copy/paste/modified from https://docs.github.com/en/actions/examples/using-scripts-to-test-your-code-on-a-runner

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Podman
        run: sudo apt-get update && sudo apt-get install --yes podman

      - name: Checkout
        uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: dev-env/Dockerfile

      - name: make ci
        run: make ci
